# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('details', models.TextField()),
                ('time_from', models.CharField(max_length=10)),
                ('time_to', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('img1', models.FileField(upload_to='')),
                ('img2', models.FileField(upload_to='')),
                ('img3', models.FileField(upload_to='')),
                ('img4', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
    ]
