# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170919_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bid',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='time_from',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bid',
            name='time_to',
            field=models.CharField(max_length=100),
        ),
    ]
