# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170919_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='item_name',
            field=models.CharField(default='testing order', max_length=255),
            preserve_default=False,
        ),
    ]
