# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bid_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('time_from', models.CharField(max_length=100)),
                ('time_to', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Заказы звонков',
                'verbose_name': 'Заказ звонка',
            },
        ),
    ]
