# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_callback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
