# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171002_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
